// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeIdentity) Reset() {
	*x = EdgeIdentity{}
	mi := &file_api_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeIdentity) ProtoMessage() {}

func (x *EdgeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeIdentity.ProtoReflect.Descriptor instead.
func (*EdgeIdentity) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EdgeIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EdgeIdentity) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Command) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TsUnixNano    int64                  `protobuf:"varint,4,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Event) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Register
	//	*Envelope_Command
	//	*Envelope_Event
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_control_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetRegister() *EdgeIdentity {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Envelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Envelope) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Register struct {
	Register *EdgeIdentity `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // sent once by the edge
}

type Envelope_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"` // supervisor -> edge
}

type Envelope_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"` // edge -> supervisor
}

func (*Envelope_Register) isEnvelope_Body() {}

func (*Envelope_Command) isEnvelope_Body() {}

func (*Envelope_Event) isEnvelope_Body() {}

var File_api_control_proto protoreflect.FileDescriptor

const file_api_control_proto_rawDesc = "" +
	"\n" +
	"\x11api/control.proto\x12\acontrol\"]\n" +
	"\fEdgeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"^\n" +
	"\aCommand\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"~\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12 \n" +
	"\fts_unix_nano\x18\x04 \x01(\x03R\n" +
	"tsUnixNano\"\x9d\x01\n" +
	"\bEnvelope\x123\n" +
	"\bregister\x18\x01 \x01(\v2\x15.control.EdgeIdentityH\x00R\bregister\x12,\n" +
	"\acommand\x18\x02 \x01(\v2\x10.control.CommandH\x00R\acommand\x12&\n" +
	"\x05event\x18\x03 \x01(\v2\x0e.control.EventH\x00R\x05eventB\x06\n" +
	"\x04body2E\n" +
	"\x0eControlService\x123\n" +
	"\aControl\x12\x11.control.Envelope\x1a\x11.control.Envelope(\x010\x01B8Z6local.dev/opamp-poc-supervisor/api/controlpb;controlpbb\x06proto3"

var (
	file_api_control_proto_rawDescOnce sync.Once
	file_api_control_proto_rawDescData []byte
)

func file_api_control_proto_rawDescGZIP() []byte {
	file_api_control_proto_rawDescOnce.Do(func() {
		file_api_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)))
	})
	return file_api_control_proto_rawDescData
}

var file_api_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_control_proto_goTypes = []any{
	(*EdgeIdentity)(nil), // 0: control.EdgeIdentity
	(*Command)(nil),      // 1: control.Command
	(*Event)(nil),        // 2: control.Event
	(*Envelope)(nil),     // 3: control.Envelope
}
var file_api_control_proto_depIdxs = []int32{
	0, // 0: control.Envelope.register:type_name -> control.EdgeIdentity
	1, // 1: control.Envelope.command:type_name -> control.Command
	2, // 2: control.Envelope.event:type_name -> control.Event
	3, // 3: control.ControlService.Control:input_type -> control.Envelope
	3, // 4: control.ControlService.Control:output_type -> control.Envelope
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_control_proto_init() }
func file_api_control_proto_init() {
	if File_api_control_proto != nil {
		return
	}
	file_api_control_proto_msgTypes[3].OneofWrappers = []any{
		(*Envelope_Register)(nil),
		(*Envelope_Command)(nil),
		(*Envelope_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_control_proto_rawDesc), len(file_api_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_proto_goTypes,
		DependencyIndexes: file_api_control_proto_depIdxs,
		MessageInfos:      file_api_control_proto_msgTypes,
	}.Build()
	File_api_control_proto = out.File
	file_api_control_proto_goTypes = nil
	file_api_control_proto_depIdxs = nil
}
